export const SEED = {
  escolas: [],
  turnos: [],
  modalidades: [],
  tiposRefeicao: [],
  meses: [],
  categorias: [],
  subcategorias: [],
  insumos: [],
  tiposRefeicaoCardapio: [],
  cardapios: [],
  lancamentos: [],
  mesesFechados: [],
  fechamentos: [],
  usuarios: [
    { id: "u1", nomeCompleto: "Nutricionista SEME", login: "NUTRI.SEME", senha: "123", email: "nutri.seme@seme.gov.br", cargo: "Nutricionista", nivelAcesso: "nutricionista", escolaId: null, localTrabalho: "SEME", telefone: "" },
    { id: "u2", nomeCompleto: "Escola SEME", login: "ESCOLA.SEME", senha: "123", email: "escola.seme@seme.gov.br", cargo: "Merendeira", nivelAcesso: "escola", escolaId: null, localTrabalho: "", telefone: "" },
    { id: "u3", nomeCompleto: "Administrador Geral", login: "ADM.SEME", senha: "1898", email: "adm.seme@seme.gov.br", cargo: "Administrador Geral", nivelAcesso: "admin", escolaId: null, localTrabalho: "SEME", telefone: "" },
    { id: "u4", nomeCompleto: "Empresa SEME", login: "EMPRESA.SEME", senha: "123", email: "empresa.seme@seme.gov.br", cargo: "Empresa Fornecedora", nivelAcesso: "empresa", escolaId: null, localTrabalho: "", telefone: "" },
  ],
  solicitacoes: [],
  historico: [],
  notificacoes: [],
};
